/*
 *  This file is part of the Maxwell Word Processor application.
 *  Copyright (C) 1996, 1997, 1998 Andrew Haisley, David Miller, Tom Newton
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
/*
 * MODULE : maxwell.C
 *
 * AUTHOR : Andrew Haisley
 *
 * This file
 *
 * DESCRIPTION:
 *
 *
 *
 */

#include <X11/Intrinsic.h>

#include <locale.h>
#include <pwd.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#include <iostream>
#include <filesystem>

#include <mx.h>
#include <mx_db.h>

#include <maxwell.h>

#include <mx_language.h>
#include <mx_app.h>
#include <mx_config.h>
#include <mx_support_d.h>

#include <mx_xpm.h>
#include <mx_resources.h>

using namespace std;

// the one and only app
static mx_app* app = nullptr;

// the name of the file used to lock the display sort of
static char lock_file_name[MAX_PATH_LEN];

Widget global_top_level;
XtAppContext global_app_context;
mx_config* global_user_config;
char* global_maxhome;

/*
 * PROCEDURE : error_exit
 * ACTION    : called on an error which forces maxwell to exit. tries to
 *           : clean up neatly.
 * ARGS      : none
 *
 */
static void error_exit()
{
    int err = MX_ERROR_OK;

    if (app != nullptr) {
        app->stop(err);
        app->unlock();
    }

    unlink(lock_file_name);
    exit(1);
}

/*
 * PROCEDURE : mx_handle_warn
 * ACTION    : handles warning generated by the Xt stuff
 * ARGS      : a string with a description in it
 *
 */
static void mx_handle_warn(String m)
{
    fprintf(stderr, "WARNING:%s\n", m);
}

/*
 * PROCEDURE : mx_handle_error
 * ACTION    : handles Xt errors
 *
 */
static void mx_handle_error(String m)
{
    fprintf(stderr, "ERROR:%s\n", m);
}

/*
 * PROCEDURE : child_sigproc
 * ACTION    : repsonds to SIG_CHLD - only action is to stop zombie
 *           : processes from building up in a long run
 * ARGS      : none
 *
 */
static int child_sigproc()
{
    int s;

    // get rid of zombies
    (void)wait(&s);

    signal(SIGCLD, (sighandler_t)child_sigproc);
    return 0;
}

/*
 * PROCEDURE : get_display_name
 * ACTION    : figures out the X display name
 * ARGS      : command line args used to figure the display.
 *
 */
static void get_display_name(int argc, char* argv[], char* dn)
{
    char hn[100];
    int i;

    if (gethostname(hn, 99) < 0) {
        strcpy(hn, "localhost");
    } else {
        hn[99] = 0;
    }

    strcpy(dn, "");

    // is display in the arglist
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-display") == 0) {
            if (i != (argc - 1)) {
                strcpy(dn, argv[i + 1]);
                break;
            }
        }
    }

    if (strlen(dn) == 0) {
        // next, is DISPLAY in the environment ?
        if (getenv("DISPLAY") != nullptr) {
            strcpy(dn, getenv("DISPLAY"));
        } else {
            // no use hostname:0.0
            sprintf(dn, "%s:0.0", hn);
        }
    }
}

/*
 * PROCEDURE : check_display
 * ACTION    : makes sure that the display can be opened. Also, prints a simple
 *           : message if it it can't.
 * ARGS      : command line args used to figure the display.
 *
 */
static void check_display(int argc, char* argv[])
{
    char dn[100];
    Display* d;

    get_display_name(argc, argv, dn);

    d = XOpenDisplay(dn);
    if (d == nullptr) {
        printf("ERROR:Maxwell was unable to open the display %s.\n", dn);
        error_exit();
    } else {
        XCloseDisplay(d);
    }
}

/*
 * PROCEDURE : merge_resources
 * ACTION    : merges in the maxwell resource file
 *
 */
void merge_resources()
{
    XrmDatabase db = nullptr;
    char file_name[MAX_PATH_LEN];

    db = XtDatabase(XtDisplay(global_top_level));
    if (db == nullptr) {
        fprintf(stderr, "ERROR:couldn't get resource DB\n");
        error_exit();
    }

    sprintf(file_name, "%s/maxwell.rsc", global_maxhome);

    mx_write_x_resources_needed(file_name);

    if (!XrmCombineFileDatabase(file_name, &db, True)) {
        fprintf(stderr, "ERROR:couldn't combine resource DBs\n");
        error_exit();
    }
}

/*
 * PROCEDURE : open_config
 * ACTION    : opens the users config file - if there isn't one, create one from the
 *           : system default config
 * ARGS      : error
 *
 */
static void open_config(int& err)
{
    char temp[MAX_PATH_LEN];
    uid_t uid;

    struct passwd* pw;

    uid = getuid();
    pw = getpwuid(uid);

    sprintf(temp, "%s/%s", pw->pw_dir, ".maxwellrc");
    global_user_config = new mx_config(err, temp);
    if (err != MX_ERROR_OK) {
        FILE *f = fopen(temp, "w");
        if (f == nullptr)
        {
            fprintf(stderr, "ERROR:Couldn't create user defaults file %s\n", temp);
            error_exit();
        }

        fprintf(f, "language:en_US\n");
        fprintf(f, "units:inches\n");
        fprintf(f, "printer:EPSON_ET_2800_Series_USB\n");
        fprintf(f, "page:A4\n");
        fprintf(f, "envelope:DL\n");

        fclose(f);

        global_user_config = new mx_config(err, temp);
        MX_ERROR_CHECK(err);
    }
abort:;
}

/*
 * PROCEDURE : open_config
 * ACTION    : adds the maxwell bitmaps directory into the X server bitmap search path
 *
 */
static void set_bitmap_path()
{
    static char temp[MAX_PATH_LEN];
    char* lp;

    // set the bitmap path
    lp = getenv("XBMLANGPATH");
    if (lp == nullptr) {
        sprintf(temp, "%s/xpm/%%B", global_maxhome);
    } else {
        sprintf(temp, "%s/xpm/%%B:%s", global_maxhome, lp);
    }
    setenv("XBMLANGPATH", temp, true);
    unsetenv("XAPPLRESDIR");
}

/*
 * PROCEDURE : open_wp_file
 * ACTION    : attempts to open a named document file. prints errors if it can't
 * RETURNS   : nullptr on failure, a document pointer otherwise
 *
 */
static mx_wp_document* open_wp_file(char* name)
{
    mx_wp_document* res;

    int err = MX_ERROR_OK;

    // try to open it - set recover flag, so never fail for that reason
    res = mx_db_client_open_wp_doc(err, name, true);
    if (err != MX_ERROR_OK) {

        if (err == MX_FILE_UNRECOVERABLE) {
            printf("WARNING:sorry, file %s is damaged beyond recovery\n", name);
            MX_ERROR_CLEAR(err);

            return nullptr;
        }

        else {
            MX_ERROR_CLEAR(err);
            return nullptr;
        }
    } else {
        return res;
    }
}

static void handle_args(int argc, char* argv[])
{
    int err = MX_ERROR_OK;
    mx_wp_document* doc;

    // were there any files on the command line? Locking is handled a bit
    // differently here as the windows haven't been realised yet.....
    if (argc > 1) {
        for (int i = 1; i < argc; i++) {
            if (mx_is_file_type(argv[i], mx_document_file_e)) {
                if (!app->is_doc_open(argv[i])) {
                    doc = open_wp_file(argv[i]);
                    if (doc != nullptr) {
                        app->new_wp_editor(err, doc);
                        MX_ERROR_CHECK(err);
                    }
                }
            } else {
                printf("WARNING:sorry, can't open non-Maxwell files from command line\n");
            }
        }
    }
    return;
abort:
    MX_ERROR_CLEAR(err);
}

/*
 * PROCEDURE : set_signals
 * ACTION    : sets up signal handlers for various things
 *
 */
static void set_signals()
{
    signal(SIGCLD, (sighandler_t)child_sigproc);
    signal(SIGCLD, SIG_IGN);
}

// the maxwell top level. Creates the main window with start
// buttons for each variety of maxwell app. currently just the
// WP app of course.
int main(int argc, char* argv[])
{
    int err = MX_ERROR_OK;

    setlocale(LC_ALL, "");

    strcpy(lock_file_name, "");

    XtAppSetWarningHandler(global_app_context, mx_handle_warn);
    XtAppSetErrorHandler(global_app_context, mx_handle_error);

    set_signals();

    global_maxhome = getenv("MAXHOME");

    if (global_maxhome == nullptr) {
        auto pw = getpwuid(getuid());
        std::string dir = pw->pw_dir;
        dir += "/.maxwell";
        global_maxhome = strdup(dir.c_str());
    } else {
        global_maxhome = strdup(global_maxhome);
    }

    std::filesystem::path dir_path = global_maxhome;

    if (!std::filesystem::exists(dir_path)) {
        std::filesystem::create_directory(dir_path);
    }

    dir_path = std::string(global_maxhome) + "/xpm";

    if (!std::filesystem::exists(dir_path)) {
        std::filesystem::create_directory(dir_path);
    }

    dir_path = std::string(global_maxhome) + "/metrics";

    if (!std::filesystem::exists(dir_path)) {
        std::filesystem::create_directory(dir_path);
    }

    mx_xpm_write_bitmaps_if_needed(std::string(global_maxhome) + "/xpm");

    open_config(err);
    MX_ERROR_CHECK(err);

    mx_db_client_login(err);
    MX_ERROR_CHECK(err);

    // get the bitmaps into the path
    set_bitmap_path();

    check_display(argc, argv);

    global_top_level = XtVaAppInitialize(&global_app_context, "Maxwell", nullptr, 0, &argc, argv, nullptr, nullptr);

    // set up the X resources
    merge_resources();

    global_error_trace->init_exit_proc(error_exit);

    // read list of supported languages
    mx_language::init();

    // get the app ready to open files and stuff
    app = mx_app::init();

    handle_args(argc, argv);
    MX_ERROR_CHECK(err);

    {
        // print up a copyright dialog
        mx_support_d d(app->get_widget());
        d.run();
    }

    // off it goes..........
    app->run(err);
    MX_ERROR_CHECK(err);

    app->stop(err);
    MX_ERROR_CHECK(err);

    return 0;

abort:
    global_error_trace->print();
    return -1;
}
